included:
    - Equinox
    - EquinoxCore
    - EquinoxUI
    - EquinoxAssets
opt_in_rules:
    - attributes
    - block_based_kvo
    - class_delegate_protocol
    - closing_brace
    - closure_end_indentation
    - closure_parameter_position
    - closure_spacing
    - collection_alignment
    - colon
    - comma
    - compiler_protocol_init
    - conditional_returns_on_newline
    - contains_over_first_not_nil
    - control_statement
    - convenience_type
    - discouraged_direct_init
    - discouraged_object_literal
    - duplicate_imports
    - dynamic_inline
    - empty_count
    - empty_enum_arguments
    - empty_parameters
    - empty_parentheses_with_trailing_closure
    - empty_string
    - empty_xctest_method
    - explicit_init
    - fallthrough
    - fatal_error_message
    - file_length
    - first_where
    - for_where
    - force_cast
    - force_try
    - force_unwrapping
    - function_body_length
    - function_default_parameter_at_end
    - function_parameter_count
    - identical_operands
    - implicit_getter
    - inert_defer
    - large_tuple
    - last_where
    - leading_whitespace
    - legacy_cggeometry_functions
    - legacy_constant
    - legacy_constructor
    - legacy_hashing
    - legacy_random
    - let_var_whitespace
    - line_length
    - mark
    - multiline_literal_brackets
    - nesting
    - number_separator
    - opening_brace
    - operator_usage_whitespace
    - operator_whitespace
    - private_over_fileprivate
    - protocol_property_accessors_order
    - redundant_discardable_let
    - return_arrow_whitespace
    - shorthand_operator
    - sorted_first_last
    - sorted_imports
    - statement_position
    - switch_case_alignment
    - syntactic_sugar
    - todo
    - trailing_closure
    - trailing_comma
    - trailing_newline
    - trailing_semicolon
    - type_name
    - unneeded_break_in_switch
    - unneeded_parentheses_in_closure_argument
    - unused_closure_parameter
    - unused_control_flow_label
    - unused_enumerated
    - unused_setter_value
    - vertical_parameter_alignment
    - vertical_whitespace
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - void_return
    - weak_delegate
    - type_body_length
disabled_rules:
    - trailing_whitespace
analyzer_rules:
    - explicit_self
    - unused_declaration
    - unused_import

line_length: 150

type_body_length:
    warning: 300
    error: 400
    
file_length:
    warning: 500
  
function_parameter_count:
    warning: 6
    error: 20

nesting:
    type_level:
        warning: 3
        error: 6

identifier_name:
    min_length: 2
    
type_name:
    min_length: 3
    max_length: 50

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
