name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: xcode-27
    steps:
      - uses: actions/checkout@master
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '27.0'

      - name: Test
        run: sh build/test.sh

      - name: Build
        run: sh build/build.sh
